spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
#    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    cache-names: user

logging:
  level:
    root: INFO                        # Default for everything
    com.yourproject.package: DEBUG    # Detailed logs for your code
    org.hibernate.SQL: DEBUG          # See the actual SQL queries being sent to DB
    org.springframework.cahce: TRACE

  file:
    name: logs/application.log        # Path to the log file

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,caches,loggers, metrics"





